/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#EF4444',
        'primary-hover': '#DC2626',
        'primary-dark': '#B91C1C',
        secondary: '#F97316',
        'secondary-hover': '#EA580C',
        background: '#FAFAF9',
        'canvas-base': '#FAFAF9',
        surface: '#FFFFFF',
        'surface-card': '#FFFFFF',
        'surface-raised': '#F5F5F4',
        'surface-dim': '#F0EDE8',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#FAF8F5',
        'surface-container': '#F5F5F4',
        'surface-container-high': '#EAE5DF',
        'surface-container-highest': '#E2DCD5',
        'border-subtle': '#E7E5E4',
        'border-prominent': '#D6D3D1',
        'text-primary': '#0C0A09',
        'text-secondary': '#57534E',
        'text-muted': '#78716C',
        'on-surface': '#0C0A09',
        'on-surface-variant': '#57534E',
        'on-background': '#0C0A09',
        'red-50': '#FEF2F2',
        'red-100': '#FEE2E2',
        'red-200': '#FECACA',
        'red-400': '#F87171',
        'red-500': '#EF4444',
        'red-600': '#DC2626',
        'red-700': '#B91C1C',
        'orange-50': '#FFF7ED',
        'orange-100': '#FFEDD5',
        'orange-200': '#FED7AA',
        'orange-400': '#FB923C',
        'orange-500': '#F97316',
        'orange-600': '#EA580C',
        'neutral-50': '#FAFAF9',
        'neutral-100': '#F5F5F4',
        'neutral-200': '#E7E5E4',
        'neutral-300': '#D6D3D1',
        'neutral-400': '#A8A29E',
        'neutral-500': '#78716C',
        'neutral-600': '#57534E',
        'neutral-700': '#44403C',
        'neutral-800': '#292524',
        'neutral-900': '#1C1917',
        'neutral-950': '#0C0A09',
        // Dark mode surfaces
        'dark-bg': '#0C0A09',
        'dark-surface': '#1C1917',
        'dark-surface-raised': '#292524',
        'dark-border': '#44403C',
        'dark-border-subtle': '#292524',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'space-2xs': '0.125rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-base': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        gutter: '1.25rem',
        'gutter-mobile': '0.75rem',
        margin: '2rem',
        'margin-mobile': '1rem',
      },
      fontFamily: {
        geist: ['Geist', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        'display-hero': ['44px', { lineHeight: '52px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'display-hero-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['22px', { lineHeight: '30px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '400' }],
        'stat-label': ['11px', { lineHeight: '16px', letterSpacing: '0.06em', fontWeight: '500' }],
        'stat-value': ['22px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'badge-label': ['10px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '600' }],
        'control-label': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'code-block': ['13px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
      },
      boxShadow: {
        xs: '0 1px 2px 0 rgba(12, 10, 9, 0.04)',
        sm: '0 1px 3px 0 rgba(12, 10, 9, 0.06), 0 1px 2px -1px rgba(12, 10, 9, 0.04)',
        card: '0 2px 8px 0 rgba(12, 10, 9, 0.06)',
        'card-hover': '0 4px 16px 0 rgba(12, 10, 9, 0.1)',
      },
      keyframes: {
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'count-up': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in-up': 'fade-in-up 0.4s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'fade-in': 'fade-in 0.3s ease-out forwards',
        shimmer: 'shimmer 1.5s infinite linear',
        'count-up': 'count-up 0.5s cubic-bezier(0.22, 1, 0.36, 1) forwards',
      },
    },
  },
  plugins: [],
};
